version: "3.8"
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment: 
      - FLASK_APP=flask_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_bmg
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: 
      - db
      - redis
    networks: 
      - flask_network
  db:
    container_name: postgres
    image: postgres:13.4
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_bmg
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - flask_network
  redis:
    container_name: redis
    image: redis:6.0.15
    ports: 
      - 6379:6379
    networks: 
      - flask_network

volumes: 
  pgdata:

networks: 
  flask_network:
    name: flask_network
  